/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    'static-content': StaticContent;
    projects: Project;
    companies: Company;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'static-content': StaticContentSelect<false> | StaticContentSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  titulo: string;
  descripcion: string;
  proveedor: string;
  url: string;
  esGratuito?: boolean | null;
  nivel: 'basico' | 'intermedio' | 'avanzado';
  duracionHoras?: number | null;
  imagen?: (number | null) | Media;
  destacado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-content".
 */
export interface StaticContent {
  id: number;
  titulo: string;
  slug: string;
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tipo: 'pagina' | 'faq' | 'noticia';
  updatedAt: string;
  createdAt: string;
}
/**
 * Ofertas laborales publicadas
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  titulo: string;
  /**
   * Selecciona la empresa que publica esta oferta
   */
  company: number | Company;
  /**
   * Describe las funciones y responsabilidades principales
   */
  descripcion: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Requisitos académicos y técnicos necesarios
   */
  requisitos: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Para sugerir cursos CAPACÍTATE relacionados
   */
  skills_requeridas?: string | null;
  nivel_experiencia: 'sin_experiencia' | 'menos_1_anio' | '1_3_anios' | 'mas_3_anios';
  carreras_afines?: string | null;
  modalidad: 'presencial' | 'remoto' | 'hibrido';
  /**
   * Solo si la modalidad NO es remoto
   */
  ubicacion?: {
    departamento?: string | null;
    distrito?: string | null;
    direccion?: string | null;
  };
  tipo_contrato: 'practicas_pre' | 'practicas_pro' | 'tiempo_completo' | 'medio_tiempo' | 'por_horas' | 'freelance';
  horario?: string | null;
  compensacion?: {
    salario_min?: number | null;
    salario_max?: number | null;
    /**
     * Si está desmarcado, se mostrará "A convenir"
     */
    mostrar_salario?: boolean | null;
  };
  beneficios?: string | null;
  /**
   * Si está vacío, se usará el email de la empresa
   */
  email_contacto?: string | null;
  instrucciones_postulacion?: string | null;
  /**
   * Solo las ofertas "Activas" se muestran públicamente
   */
  estado: 'borrador' | 'activa' | 'pausada' | 'cerrada';
  fecha_publicacion?: string | null;
  /**
   * Hasta cuándo se aceptan postulaciones
   */
  fecha_cierre?: string | null;
  /**
   * Las ofertas destacadas aparecen primero
   */
  destacada?: boolean | null;
  /**
   * Se mostrará una badge de "Urgente"
   */
  urgente?: boolean | null;
  /**
   * Se genera automáticamente del título
   */
  slug: string;
  /**
   * Se actualiza automáticamente
   */
  vistas?: number | null;
  /**
   * Se actualiza desde el backend
   */
  postulaciones_count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Empresas que publican ofertas laborales
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  nombre_comercial: string;
  razon_social?: string | null;
  ruc?: string | null;
  sector:
    | 'tecnologia'
    | 'construccion'
    | 'manufactura'
    | 'servicios'
    | 'educacion'
    | 'salud'
    | 'retail'
    | 'finanzas'
    | 'consultoria'
    | 'otro';
  descripcion?: string | null;
  sitio_web?: string | null;
  /**
   * Logo que aparecerá en las ofertas
   */
  logo?: (number | null) | Media;
  /**
   * Las empresas con convenio aparecen destacadas
   */
  tiene_convenio?: boolean | null;
  /**
   * Email principal para recibir postulaciones
   */
  email_contacto: string;
  telefono_contacto?: string | null;
  persona_contacto?: string | null;
  direccion?: string | null;
  /**
   * Desactivar si ya no publica ofertas
   */
  activo?: boolean | null;
  /**
   * Se genera automáticamente del nombre
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'static-content';
        value: number | StaticContent;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  proveedor?: T;
  url?: T;
  esGratuito?: T;
  nivel?: T;
  duracionHoras?: T;
  imagen?: T;
  destacado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-content_select".
 */
export interface StaticContentSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  contenido?: T;
  tipo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  titulo?: T;
  company?: T;
  descripcion?: T;
  requisitos?: T;
  skills_requeridas?: T;
  nivel_experiencia?: T;
  carreras_afines?: T;
  modalidad?: T;
  ubicacion?:
    | T
    | {
        departamento?: T;
        distrito?: T;
        direccion?: T;
      };
  tipo_contrato?: T;
  horario?: T;
  compensacion?:
    | T
    | {
        salario_min?: T;
        salario_max?: T;
        mostrar_salario?: T;
      };
  beneficios?: T;
  email_contacto?: T;
  instrucciones_postulacion?: T;
  estado?: T;
  fecha_publicacion?: T;
  fecha_cierre?: T;
  destacada?: T;
  urgente?: T;
  slug?: T;
  vistas?: T;
  postulaciones_count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  nombre_comercial?: T;
  razon_social?: T;
  ruc?: T;
  sector?: T;
  descripcion?: T;
  sitio_web?: T;
  logo?: T;
  tiene_convenio?: T;
  email_contacto?: T;
  telefono_contacto?: T;
  persona_contacto?: T;
  direccion?: T;
  activo?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}